@url = https://google.com
# @url = http://localhost:5000
@access_token =

GET {{url}}/search?q=hehe

### sample get
GET http://google.com


###
GET http://localhost:5000/users/me/



### Get Token
POST http://localhost:5000/token
Content-Type: application/x-www-form-urlencoded

username=tim&password=tim1234

### Use Token
GET http://localhost:5000/auth/me
Authorization: Bearer {{access_token}}

###
@url = http://localhost:5000
@token = 

# 🔐 Get auth token
POST {{url}}/login
Content-Type: application/json

{
  "username": "your_username",
  "password": "your_password"
}

> {% 
  const body = JSON.parse(response.body);
  client.global.set("token", body.token);
%}

###

# 💌 Example Authenticated GET Request
GET {{url}}/protected-route
Authorization: Bearer {{token}}

###

# 🛠 Example POST with Auth
POST {{url}}/some-endpoint
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "data": "value"
}
