### login test
POST http://localhost:5000/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=secret


### sample get
GET http://google.com


### Get Token
GET http://localhost:5000/auth/token
Content-Type: application/json

{
    "username": "sufi",
    "password": "12345"
}

### Use Token
GET http://localhost:5000/auth/me
Authorization: Bearer {{access_token}}