### Get CSRF token and cookie from /test
GET http://127.0.0.1:5001/test

### POST critical request with CSRF protection
POST http://127.0.0.1:5001/critical
Cookie: fastapi-csrf-token=IjEzMDdmNDFhY2ZhMDAwMWQ3ODZmNmVjMjM0MGQ4MTIwNDNkNzQ2MWQi.aH0VRA.cWwgjBgchogu9DbMNjffMrgLlz0
X-CSRF-Token: 1307f41acfa0001d786f6ec2340d812043d7461d
Content-Type: application/json

{}


