[project]
name = "nginx-gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.117.1",
    "httpx>=0.28.1",
    "uvicorn[standard]>=0.37.0",
]
